CREATE DATABASE api_todo;

CREATE USER user_todo;

ALTER USER user_todo WITH ENCRYPTED PASSWORD "1122";

-- Using the api_todo DATABASE, run:

CREATE TABLE todos (id SERIAL PRIMARY KEY, title VARCHAR, description TEXT, done BOOL DEFAULT false);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO user_todo;


GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO user_todo;